[base]
package = ocean
env_name = puffer_stacking
policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 4092
max_ep_steps = 300
num_containers = 200
num_stacks = None #should be None auto calcs un .py according to the paper scale spec
max_height = 4

#10c/3s/5h trains ok

[train]

adam_beta1 = 0.9582460994898264
adam_beta2 = 0.99974959592239
adam_eps = 0.00000039502871076804
anneal_lr = True
batch_size = "auto"
bptt_horizon = 64
checkpoint_interval = 200
compile = False
compile_fullgraph = True
compile_mode = "max-autotune-no-cudagraphs"
cpu_offload = False
data_dir = "experiments"
device = "cuda"
ent_coef = 0.03165133293145307
gae_lambda = 0.8533142335319223
gamma = 0.9952673707012256
learning_rate = 0.017309730368237377
max_grad_norm = 1.05677195995329
max_minibatch_size = 32768
minibatch_size = 32768
num_envs = "auto"
num_workers = "auto"
optimizer = "muon"
precision = "float32"
prio_alpha = 0.8676921355753168
prio_beta0 = 0.9544045180931338
seed = 42
total_timesteps = 160000000
update_epochs = 1
use_rnn = True
vf_clip_coef = 0.1
vf_coef = 1.8348844499793515
vtrace_c_clip = 1.0249334262088912
vtrace_rho_clip = 2.6093217232559525



#seed = 42
#
#
#gamma = 0.9735637603891184
#device = "cuda"
#compile = False
#project = "ablations"
#use_rnn = True
#vf_coef = 2.328216655893854
#adam_eps = 5.578761929164955e-7
#data_dir = "experiments"
#ent_coef = 0.011952416339058122
#num_envs = "auto"
#anneal_lr = True
#clip_coef = 0.1092901473704268
#optimizer = "muon"
#precision = "float32"
#adam_beta1 = 0.947209522231594
#adam_beta2 = 0.9998347422027546
#batch_size = "auto"
#gae_lambda = 0.924953495618038
#prio_alpha = 0.8551768701095943
#prio_beta0 = 0.908788386042268
#cpu_offload = False
#num_workers = "auto"
#bptt_horizon = 64
#compile_mode = "max-autotune-no-cudagraphs"
#vf_clip_coef = 0.22051392829033536
#learning_rate = 0.009427232076428226
#max_grad_norm = 1.6049762332629296
#update_epochs = 1
#vtrace_c_clip = 1.015244200943217
#minibatch_size = 32768
#total_timesteps = 159300769.0049237
#vtrace_rho_clip = 0.7680721084932949
#compile_fullgraph = True
#max_minibatch_size = 32768
#checkpoint_interval = 200
#torch_deterministic = True


[sweep]
method = Protein 
metric = score
goal = maximize
downsample = 10

[sweep.train.total_timesteps]
distribution = log_normal
min = 5e7
max = 1e10
mean = 1.59300769e8
scale = time

[sweep.train.bptt_horizon]
distribution = uniform_pow2
min = 16
max = 64
mean = 64
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 8192
max = 65536
mean = 32768
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
max = 0.1
mean = 0.009427232076428226
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
max = 0.2
mean = 0.011952416339058122
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
max = 0.9999
mean = 0.9735637603891184
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.6
max = 0.995
mean = 0.924953495618038
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 0.7680721084932949
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.015244200943217
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.01
max = 1.0
mean = 0.1092901473704268
scale = auto

[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.1
max = 5.0
mean = 0.22051392829033536
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.0
max = 5.0
mean = 2.328216655893854
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.6049762332629296
scale = auto

[sweep.train.adam_beta1]
distribution = logit_normal
min = 0.5
max = 0.999
mean = 0.947209522231594
scale = auto

[sweep.train.adam_beta2]
distribution = logit_normal
min = 0.9
max = 0.99999
mean = 0.9998347422027546
scale = auto

[sweep.train.adam_eps]
distribution = log_normal
min = 1e-14
max = 1e-4
mean = 5.578761929164955e-7
scale = auto

[sweep.train.prio_alpha]
distribution = logit_normal
min = 0.1
max = 0.99
mean = 0.8551768701095943
scale = auto

[sweep.train.prio_beta0]
distribution = logit_normal
min = 0.1
max = 0.99
mean = 0.908788386042268
scale = auto
