[base]
package = ocean
env_name = puffer_stacking
policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 4092
max_ep_steps = 100
num_containers = 30
num_stacks = None #should be None auto calcs un .py according to the paper scale spec
max_height = 4

#10c/3s/5h trains ok

[sweep]
method = Protein 
metric = score
goal = maximize
downsample = 10

[train]
total_timesteps = 10_000_000
gamma = 0.95
learning_rate = 0.05
minibatch_size = 32768
num_workers = auto
device= 'cpu'
num_envs = 'auto'
batch_size = 'auto'

