[base]
package = None
env_name = None
policy_name = Policy
rnn_name = None
max_suggestion_cost = 3600

[vec]
backend = Multiprocessing
num_envs = 1
num_workers = auto
batch_size = auto
zero_copy = True
seed = 42

[env]
num_envs = 1024
[policy]
[rnn]

[train]
q_lr = 1e-3
policy_lr = 1e-4
autotune = True
alpha = 0.006
buffer_size = 1e6 
learning_starts = 5e3
target_network_update_freq = 1
policy_freq = 2
tau = 0.002
gamma = 0.99
minibatch_size = 512
hidden_size = 256
train_ratio = 0.1
max_runtime = 1200 #######################NOTE: THIS IS THE MAX RUNTIME #######################
name = pufferai

project = ablations

seed = 42
torch_deterministic = True
cpu_offload = False
device = cuda
precision = float32
total_timesteps = 1_000_000

data_dir = experiments
checkpoint_interval = 200
batch_size = auto

# Accumulate gradients above this size
compile = False
compile_mode = max-autotune-no-cudagraphs
compile_fullgraph = True

[sweep]
method = Protein 
metric = score
goal = maximize
downsample = 10

#[sweep.vec.num_envs]
#distribution = uniform_pow2
#min = 1
#max = 16
#mean = 8
#scale = auto

# TODO: Elim from base
[sweep.train.total_timesteps]
distribution = log_normal
min = 50000
max = 5000000
mean = 1000000
scale = time


[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 64
max = 256
mean = 128
scale = auto

[sweep.train.q_lr]
distribution = log_normal
min = 0.00001
mean = 3e-2
max = 5e-2
scale = 0.5

[sweep.train.policy_lr]
distribution = log_normal
min = 0.00001
mean = 1e-3
max = 5e-2
scale = 0.5

[sweep.target_network_update_freq]
distribution = int_uniform
min = 0.1
max = 8
mean = 1
scale = auto

[sweep.train.policy_freq]
distribution = int_uniform
min = 1
max = 12
mean = 1
scale = 2.0

[sweep.train.tau]
distribution = log_normal
min = 0.00001
mean = 0.1
max = 0.5
scale = 0.5

[sweep.train.gamma]
distribution = log_normal
min = 0.8
mean = 0.95
max = 0.9999
scale = auto

[sweep.train.hidden_size]
distribution = uniform_pow2
min = 64
max = 512
mean = 128
scale = auto

[sweep.train.learning_starts]
distribution = log_normal
min = 50000      
mean = 80000    
max = 200000    
scale = 0.5

[sweep.train.train_ratio]
distribution = uniform
min = 0.001
max = 0.2
mean = 0.1
scale = auto
