[base]
package = None
env_name = None
policy_name = Policy
rnn_name = None
max_suggestion_cost = 3600

[vec]
backend = Multiprocessing
num_envs = 2
num_workers = auto
batch_size = auto
zero_copy = True
seed = 42

[env]
num_envs = 4
[policy]
[rnn]

[train]
q_lr = 1e-3
policy_lr = 1e-4
autotune = False
alpha = 0.2
buffer_size = 1e6 
learning_starts = 5e3
target_network_update_freq = 1
policy_freq = 2
tau = 0.002
gamma = 0.99
minibatch_size = 512
hidden_size = 128



name = pufferai

project = ablations

seed = 42
torch_deterministic = True
cpu_offload = False
device = cuda
precision = float32
total_timesteps = 10_000_000
learning_rate = 0.015
update_epochs = 1

data_dir = experiments
checkpoint_interval = 200
batch_size = auto

# Accumulate gradients above this size
max_minibatch_size = 32768
compile = False
compile_mode = max-autotune-no-cudagraphs
compile_fullgraph = True

[sweep]
method = Protein 
metric = score
goal = maximize
downsample = 10

#[sweep.vec.num_envs]
#distribution = uniform_pow2
#min = 1
#max = 16
#mean = 8
#scale = auto

# TODO: Elim from base
[sweep.train.total_timesteps]
distribution = log_normal
min = 5e7
max = 1e10
mean = 1e8
scale = time


[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 8192
max = 65536
mean = 32768
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
mean = 0.01
max = 0.1
scale = 0.5




