[base]
package = mujoco
env_name = HalfCheetah-v4 Hopper-v4 Swimmer-v4 Walker2d-v4 Ant-v4 Humanoid-v4 Reacher-v4 InvertedPendulum-v4 InvertedDoublePendulum-v4 Pusher-v4 HumanoidStandup-v4
policy_name = Policy
rnn_name = Recurrent

[env]
render_mode = rgb_array
exclude_current_positions_from_observation = False
terminate_when_unhealthy = False

[vec]
#512,280
num_envs = 512 
#4,28 
num_workers = 4
batch_size = auto

[train]



